name: Build plugin
on:
  push:
    tags:
      - "*"
env:
  PLUGIN_NAME: logseq-roam-theme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: |
          mkdir ${{ env.PLUGIN_NAME }} # folder for zip
          cp LICENSE README.md custom.css package.json ${{ env.PLUGIN_NAME }} # move build assets
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }} # create zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
          files: |
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.PLUGIN_NAME }}/
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"